<p><a href="<?php echo $this->url(array('controller' => 'category','action' => 'sign'),'default',true) ?>"><button>Kategorie Anlageformular</button></a></p>


<table style="width:100%" border="0">
	<tr>
		<td style="width:20%;"></td>
		<td style="width:60%;">
			<table style="width:100%">
				<tr>
					<td>
						<h3>Kategorie-Eintr&auml;ge anzeigen</h3>
					</td>
				</tr>			
			</table>
			<table style="width:100%;" border="1">
				<tr>
					<td><b>Name</b></td>
					<td><b>Beschreibung</b></td>
					<td>&nbsp;</td>
				</tr>
			    <?php foreach ($this->entries as $entry): ?>
                <tr>
                	<td style="width:42%;">
                		<?php echo $this->escape($entry->catName) ?>
                		<!--                 		
                		<input style="width:100%" type="text" name="frmCatName" value="<?php echo $this->escape($entry->catName) ?>">
                		-->
                	</td>
                	<td style="width:42%;">
                		<?php echo $this->escape($entry->catDescription) ?>
                		<!-- 
                		<input style="width:100%" type="text" name="frmCatDescription" value="<?php echo $this->escape($entry->catDescription) ?>">
                		-->                		
                	</td>
                	
                	<td style="width:16%;text-align:center;">
                		<!-- Einzelnen Datensatz anzeigen -->
                		<a href="<?= $this->url(array('controller' => 'category', 'action' => 'show', 'id' => $this->escape($entry->catID))) ?>"><button>detail</button></a>
                		                		                		
                		<!-- Datensatz bearbeiten/editieren -->
                		<a href="<?= $this->url(array('controller' => 'category', 'action' => 'edit', 'id' => $this->escape($entry->catID))) ?>"><button>edit</button></a>                		
                		
                		<!-- Datensatz loeschen -->
                		<a href="<?= $this->url(array('controller' => 'category', 'action' => 'deleteinfo', 'id' => $this->escape($entry->catID))) ?>"><button>delete</button></a>                		                		
                	</td>
                </tr>                    
                <?php endforeach ?>
			</table>
		</td>
		<td style="width:20%;"></td>
	</tr>
</table>