<h3>[-Anzeige des ausgew&auml;hlten Items-]</h3>

<p><b>ID:</b>&nbsp;<?= $this->entry['iteID'] ?></p>
<p><b>Titel:</b>&nbsp;<?= $this->entry['iteTitle'] ?></p>
<p><b>Beschreibung:</b>&nbsp;<?= $this->entry['iteDescription'] ?></p>
<p><b>Kategorie:</b>&nbsp;<?= $this->entry['catName'] ?></p>
<p><b>Box:</b>&nbsp;<?= $this->entry['boxNo'] ?></p>
<p><b>Box-Ort:</b>&nbsp;<?= $this->entry['boxPlace'] ?></p>